---
- name: Update cache and install required packages to allow using HTTPS repository
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: Create keyrings directory for Docker
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Get system architecture
  shell: dpkg --print-architecture
  register: system_architecture

- name: Setup repository
  apt_repository:
    repo: deb [arch={{ system_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker

- name: Update cache and install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes
